version: "3.8"

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=doom
      - POSTGRES_PASSWORD=mypasword
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend_app
    depends_on:
      - postgres
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://doom:mypasword@postgres:5432/mydb
    command: npm run start:prod
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres: